### ISSUE TITLE
move the 'rent

### ISSUE THREAD

**Issue by 16by40** [johngruen/bug-notes#16]

**Comment by 16by40** [comment]
![rent](https://cloud.githubusercontent.com/assets/9668834/5770438/5926ee16-9cf8-11e4-82f1-ac8e9a94b105.gif)

**Comment by 16by40** [comment]
now it's in a weird spot.  STYLING HALP!
![screen shot 2015-01-30 at 11 51 37 am](https://cloud.githubusercontent.com/assets/9668834/5982050/6a1122aa-a88d-11e4-9921-36abcbe972f2.png)

**Comment by peterflat** [comment]
Should be fixed
