### ISSUE TITLE
product cat. 'external monitors and recorders'

### ISSUE THREAD

**Issue by 16by40** [johngruen/bug-notes#9]
— 'monitors and recorders', not 'monitors-and-recorders'
— is in wrong format.  why is it all the way to the right?
![screen shot 2014-11-16 at 6 29 29 pm](https://cloud.githubusercontent.com/assets/9668834/5063699/bc5a5248-6dbe-11e4-944b-ae65515bcef6.png)

**Comment by peterflat** [comment]
There is a shopify level bug that took me forever to track down that has to do with how you name collections initially and _then if that name changes_.  I will try to fix this but it may make sense to just remove it completely and add something that is named similar but with a different working so the shopify gremlins understand
